# .golangci.yml
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  # Cyclomatic complexity checking
  cyclop:
    max-complexity: 15
    package-average: 10.0
    skip-tests: true

  # Line length checking
  lll:
    line-length: 120

  # Error checking
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - fmt.Print
      - fmt.Println
      - fmt.Printf

  # Unused variables/functions checking
  unused:
    check-exported: true

  # Formatting checking
  gofmt:
    simplify: true

  # Imports checking
  goimports:
    local-prefixes: github.com/lukeweb/k-means-algorithm-go

  # Comments checking
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - commentedOutCode
      - whyNoLint
      - unnamedResult

  # Security checking
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked (might be too restrictive)

  # Naming convention checking
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

  # Variable checking
  varcheck:
    exported-fields: true

  # Duplicate checking
  dupl:
    threshold: 150

  # Function checking
  funlen:
    lines: 80
    statements: 40

  # Nesting checking
  nestif:
    min-complexity: 4

  # Magic numbers checking (renamed from gomnd)
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers: 0,1,2,3,10,100,1000
    ignored-files:
      - ".*_test.go"

  # Interface checking (removed - deprecated)
  # interfacer was deprecated and removed

  # Code structure checking
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

  # Shadow checking (separate linter now)
  shadow:
    strict: true

  # Performance checking
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  # Test checking
  testpackage:
    skip-regexp: (export|internal)_test\.go

linters:
  enable:
    # Basic linters
    - errcheck      # Checks for unchecked errors
    - gosimple      # Checks for code simplifications
    - govet         # Checks for suspicious constructs
    - ineffassign   # Checks for ineffective assignments
    - staticcheck   # Set of static analysis checks
    - typecheck     # Checks types
    - unused        # Checks for unused code (replaces varcheck, deadcode, structcheck)

    # Formatting and style
    - gofmt         # Checks formatting
    - goimports     # Checks imports
    - misspell      # Checks for misspellings
    - stylecheck    # Checks code style
    - unconvert     # Checks for unnecessary conversions

    # Performance
    - prealloc      # Checks for slice preallocation opportunities

    # Security
    - gosec         # Checks for security issues

    # Complexity
    - cyclop        # Checks cyclomatic complexity
    - funlen        # Checks function length
    - nestif        # Checks for nested if statements
    - gocognit      # Checks cognitive complexity

    # Code quality
    - gocritic      # Various quality checks
    - dupl          # Checks for code duplication
    - mnd           # Checks for magic numbers (renamed from gomnd)
    - lll           # Checks line length

    # Other useful
    - bodyclose     # Checks for HTTP body closing
    - rowserrcheck  # Checks for sql.Rows errors
    - noctx         # Checks for context.Context usage
    - whitespace    # Checks for whitespace issues

  disable: []  # Removed deprecated linters

  fast: false

issues:
  exclude-dirs:
    - vendor
    - tmp
    - .git
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_test\\.go$" # Remove this line if you want to check tests
  exclude-rules:
    # Exclude some checks for tests
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - dupl
        - gocognit
        - cyclop

    # Exclude checks for main.go
    - path: main\.go
      linters:
        - mnd

    # Exclude checks for examples
    - path: examples/
      linters:
        - mnd
        - errcheck

  exclude:
    # Default exclusions for common false-positives
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
    - "func name will be used as test\\.Test.* by other packages, and that stutters; consider calling this"
    - "should have a package comment, unless it's in another file for this package"

  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
  fix: false
  uniq-by-line: true

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
        - gomnd
      severity: warning
    - linters:
        - lll
        - funlen
      severity: info