name: K-Means Algorithm in Go CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24.2
      - name: Install dependencies
        run: go mod tidy
      - name: Test
        run: go test -v ./pkg/kmeans